name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest
    container: python:3.12
    steps:
      - uses: actions/checkout@v4

      - name: Install ruff
        run: |
          python --version
          pip install --upgrade pip
          pip install ruff

      - name: Run ruff
        continue-on-error: true
        run: ruff check .

  flake8:
    runs-on: ubuntu-latest
    container: python:3.12
    steps:
      - uses: actions/checkout@v4

      - name: Install flake8
        run: |
          python --version
          pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        continue-on-error: true
        run: flake8 .

  pylint:
    runs-on: ubuntu-latest
    container: python:3.12
    steps:
      - uses: actions/checkout@v4

      - name: Install pylint
        run: |
          python --version
          pip install --upgrade pip
          pip install pylint

      - name: Run pylint
        continue-on-error: true
        run: |
          pylint . > pylint-report.txt || true

      - name: Upload pylint report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pylint-report
          path: pylint-report.txt
          retention-days: 7

  tests:
    runs-on: ubuntu-latest
    needs: [ruff, flake8, pylint]
    if: always()
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre-headless nodejs npm chromium
          npm install -g allure-commandline --unsafe-perm=true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          set +e
          pytest -m ui --alluredir=allure-results
          status=$?
          allure generate allure-results/ -o allure-report/ --single-file
          exit $status

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
          retention-days: 7

      - name: Upload allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 7

  final_job:
    runs-on: ubuntu-latest
    needs: tests
    if: always()
    steps:
      - name: Print final message
        run: echo "Пайплайн завершён"
